export default {
  translatorsSteps: [{
    title: "Pioneer (> 20K)",
    class: "pionner",
    from: 20000
  }, {
    title: "Explorer (>8.5K)",
    class: "explorer",
    from: 8500
  }, {
    title: "Adventurer (>5K)",
    class: "adventurer",
    from: 5000
  }, {
    title: "Backpacker (>2.5K)",
    class: "backpacker",
    from: 2500
  }, {
    title: "Traveler (>500)",
    class: "traveler",
    from: 500
  }],
  countries: {
    AR: "Spanish, Argentina",
    AT: "German, Austria",
    AZ: "Azerbaijani",
    BA: "Bosnian",
    BD: "Bengali",
    BG: "Bulgarian",
    BR: "Portuguese, Brazilian",
    CA: "French, Canada",
    CH: "German, Switzerland",
    CN: "Chinese Simplified",
    CO: "Spanish, Colombia",
    CZ: "Czech",
    DE: "German",
    DK: "Danish",
    EE: "Estonian",
    ES: "Spanish",
    FI: "Finnish",
    FR: "French",
    GB: "English, United Kingdom",
    GE: "Georgian",
    GR: "Greek",
    HN: "Spanish, Honduras",
    HR: "Croatian",
    HU: "Hungarian",
    ID: "Indonesian",
    IE: "Irish",
    IL: "Hebrew",
    IN: "Hindi",
    IN: "Kannada",
    IN: "Malayalam",
    IN: "Oriya",
    IN: "Tamil",
    IN: "Telugu",
    IR: "Persian",
    IS: "Icelandic",
    IT: "Italian",
    JP: "Japanese",
    KE: "Swahili",
    KH: "Khmer",
    KR: "Korean",
    LA: "Lao",
    LK: "Sinhala",
    LT: "Lithuanian",
    LU: "German, Luxembourg",
    LV: "Latvian",
    ME: "Montenegrin (Latin)",
    MG: "Malagasy",
    MM: "Mongolian",
    MX: "Spanish, Mexico",
    MY: "Malay",
    NL: "Dutch",
    NO: "Norwegian",
    NO: "Norwegian Nynorsk",
    PE: "Spanish, Peru",
    PK: "Pakistan",
    PL: "Polish",
    PT: "Portuguese",
    RO: "Romanian",
    RS: "Serbian",
    RU: "Russian",
    SE: "Swedish",
    SI: "Slovenian",
    SK: "Slovak",
    TH: "Thai",
    TR: "Turkish",
    TW: "Chinese Traditional",
    UA: "Ukrainian",
    US: "English",
    VE: "Spanish, Venezuela",
    VN: "Vietnamese"
  }
};
